Repository IFL-CAMP/simple, pull requests merged in 2018-02, with the labels that each got.

#1 Feature/travis ci
  .travis.yml
  CMakeLists.txt
  README.md
  examples/CMakeLists.txt
  msgs/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Tests

#3 Change header timestamp to long long
  examples/src/example_publisher.cpp
  msgs/include/simple_msgs/header.h
  msgs/src/header.cpp
  tests/include/test_utils.hpp
  tests/test_header.cpp
  tests/test_point_stamped.cpp
  tests/test_pose_stamped.cpp
  tests/test_quaternion_stamped.cpp
  tests/test_rotation_matrix_stamped.cpp
Labels: Bug

#4 Copy callbacks in subscriber and server copy assignments
  include/simple/server.hpp
  include/simple/subscriber.hpp
Labels: Bug

#6 Add code coverage via Codecov on Travis-CI
  .travis.yml
  CMakeLists.txt
  README.md
Labels: Tests, WIP

#5 Fix/image test
  .gitignore
  include/simple/generic_socket.hpp
  msgs/include/simple_msgs/image.hpp
  msgs/src/image.cpp
Labels: Bug
